/**
 * Created by Administrator on 2017/3/8.
 */
export const USERINFO_SIGN = 'USERINFO_SIGN';
export const TOKEN = 'TOKEN';
export const GETSPECIAL = 'GETSPECIAL';
export const GETSPECIALDETAIL = 'GETSPECIALDETAIL'
export const GETSPECIALMUSICLIST = 'GETSPECIALMUSICLIST'

// 音乐列表相关
export const SETMUSICURL = 'SETMUSICURL'
export const SETMUSICTIME = 'SETMUSICTIME'
export const SETMUSICNOWTIME = 'SETMUSICNOWTIME'
export const SETMUSICPROGRESS = 'SETMUSICPROGRESS'
export const SETPLAYMUSIC = 'SETPLAYMUSIC'
export const SETMUSICBACKGROUND = 'SETMUSICBACKGROUND'
export const SETMUSICTITLE = 'SETMUSICTITLE'
export const SETSHOWMUSIC = 'SETSHOWMUSIC'
export const PUSHMUSICLIST = 'PUSHMUSICLIST'
export const SHOWMUSICLIST = 'SHOWMUSICLIST'

//修改个人资料
//export const UPDATEPROFILE = 'UPDATEPROFILE'
